# Generated by Django 5.1.5 on 2025-04-01 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_categories_remove_post_body_comment_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.CharField(default=1, max_length=1000),
        ),
    ]
