# Generated by Django 5.1.5 on 2025-04-01 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(default='write content of your blog here.....', max_length=1000),
        ),
    ]
